version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo
    env_file:
      - .env
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rankings
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ranking-mongo-db:/data/db

volumes:
  ranking-mongo-db:
    external: true
