server {     
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name jonatanlantonio.com;

    listen [::]:443 ssl ipv6only=on;
    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/jonatanlantonio.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/jonatanlantonio.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        root /var/www/ranking-app;
        index index.html;
        try_files $uri$args $uri$args/ /index.html;
    }

    location /ranking-app/ {
        proxy_pass http://127.0.0.1:4200/;
        proxy_next_upstream error  timeout invalid_header http_500 http_502 http_503;    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 1m;
        proxy_redirect default;
    }

    location /ranking-app/api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_next_upstream error  timeout invalid_header http_500 http_502 http_503;    
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 1m;
        proxy_redirect default;
    }

    location ~* /\.(ht|git|svn|hg) {
        return 404;
    }

    # Bloquear acceso a archivos ocultos
    location ~ /\.(?!well-known).* {
        return 404;
    }
}